name: CI/CD Pipeline for To-Do

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '20'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: 03-Backend

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: [build_backend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm run dev
        working-directory: 02-Frontend

  unit_test:
    name: Build unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '20'
          
      #- name: Set up MySql
          #run:
            #sudo/directory
            #mysql create database
            
      - name: Unit test
        run: mvn test
        working-directory: 03-Backend
        
  
